name: Update Google Sheet

on:
  schedule:
    - cron: "*/2 * * * *" # Run every 2 minutes

jobs:
  update_sheet:
    runs-on: ubuntu-latest
    env:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # The version of Python you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run web scraping script
        run: python bets_scrapper/main.py
